export const ADD_CREATE_PLAYLIST_SONGS = "ADD_CREATE_PLAYLIST_SONGS";
export const TOGGLE_CREATE_PLAYLIST_SONG = "TOGGLE_CREATE_PLAYLIST_SONG";
export const ADD_CREATE_PLAYLIST_SONG = "ADD_CREATE_PLAYLIST_SONG";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
